name: data_melody_example
description: Demonstrates how to use the data_melody plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  data_melody:
    path: ../
  syncfusion_flutter_sliders: ^21.2.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true